apiVersion: v1
kind: PersistentVolume
metadata:
  name: zanata-config-pv
spec:
  capacity:
    storage: 500M
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/zanata-config-storage
