apiVersion: v1
kind: PersistentVolume
metadata:
  name: zanata-log-pv
spec:
  capacity:
    storage: 500M
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/zanata-log-storage
